config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'events/index'
  root 'events#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, only: %i[new create]
  resources :events do
    collection do
      get :future
      get :past
      get :woman
    end
    resource :attendance, only: %i[create destroy], module: :events
    resource :bookmark, only: %i[create destroy], module: :events
    resources :comments, only: %i[create destroy], module: :events
  end

  resources :notifications, only: %i[index show]
  namespace :notifications do
    resource :all_reads, only: %i[create]
  end

  namespace :mypage do
    root 'event_calendars#show'
    resource :event_calendar, only: %i[show]
    resources :notifications, only: %i[index]
    resource :notification_setting, only: %i[show update]
    resource :profile, only: %i[show update] do
      resource :avatar, only: %i[destroy], module: :profiles
    end
    resource :password_change, only: %i[show update]
  end

  namespace :api, defaults: { format: :json } do
    namespace :me do
      resources :events, only: %i[index]
    end
  end
end

app/controllers/mypage/base_controller.rb
# frozen_string_literal: true

class Mypage::BaseController < ApplicationController
  layout 'mypage/layouts/application'
  before_action :require_login
end

app/controllers/mypage/event_calendars_controller.rb
# frozen_string_literal: true

class Mypage::EventCalendarsController < Mypage::BaseController
  def show
    @bookmark_events = current_user.bookmark_events
    @future_events = current_user.attend_events.future
    @past_events = current_user.attend_events.past
  end
end

app/controllers/mypage/notification_settings_controller.rb
# frozen_string_literal: true

class Mypage::NotificationSettingsController < Mypage::BaseController
  def show
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_back(fallback_location: root_path, success: '更新しました')
    else
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(notification_timing_ids: [])
  end
end

app/controllers/mypage/notifications_controller.rb
# frozen_string_literal: true

class Mypage::NotificationsController < Mypage::BaseController
  def index
    @notifications = current_user.notifications.with_avatar.order(created_at: :desc).page(params[:page])
  end
end

app/controllers/mypage/password_changes_controller.rb
# frozen_string_literal: true

class Mypage::PasswordChangesController < Mypage::BaseController
  def show; end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_params)
      redirect_to mypage_password_change_path, success: 'パスワードを変更しました'
    else
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/mypage/profiles/avatars_controller.rb
# frozen_string_literal: true

class Mypage::Profiles::AvatarsController < Mypage::BaseController
  def destroy
    current_user.avatar.purge
    redirect_back(fallback_location: root_path, success: '削除しました')
  end
end

app/controllers/mypage/profiles_controller.rb
# frozen_string_literal: true

class Mypage::ProfilesController < Mypage::BaseController
  def show
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(profile_params)
      redirect_to mypage_profile_path, success: 'プロフィールを更新しました'
    else
      render :show
    end
  end

  private

  def profile_params
    params.require(:user).permit(:name, :avatar)
  end
end

app/controllers/mypage/tops_controller.rb
# frozen_string_literal: true

class Mypage::TopsController < Mypage::BaseController
  def show
    @events = current_user.attend_events.limit(4)
  end
end

app/views/mypage/profiles/show.html.erb
<div class="card">
  <!-- Card header -->
  <div class="card-header">
    <h3 class="mb-0">プロフィール</h3>
  </div>
  <!-- Card body -->
  <div class="card-body">
    <%= form_with model: @user, url: mypage_profile_path do |f|  %>
      <div class="d-lg-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center mb-4 mb-lg-0">
          <%= image_tag @user.decorate.avatar, class: 'avatar-xl rounded-circle' %>
          <div class="ms-3">
            <h4 class="mb-3">Your avatar</h4>
            <%= f.file_field :avatar %>
          </div>
        </div>
        <div>
          <%= f.submit "更新", class: "btn btn-outline-white btn-sm" %>
          <% if @user.avatar.attached? %>
            <%= link_to "削除", mypage_profile_avatar_path, class: "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: "削除します" } %>
          <% end %>
        </div>
      </div>
    <% end %>
    <hr class="my-5">
    <div>
      <h4 class="mb-0">Personal Details</h4>
      <p class="mb-4">
        Edit your personal information and address.
      </p>
      <!-- Form -->
      <%= form_with(model: @user, url: mypage_profile_path) do |f| %>
        <div class="mb-3">
          <%= f.label :email, class: 'form-label' %>
          <%= f.email_field :email, class: 'form-control', required: true, placeholder: 'Email' %>
        </div>
        <div class="mb-3">
          <%= f.label :name, class: 'form-label' %>
          <%= f.text_field :name, class: 'form-control', placeholder: 'らんてくん' %>
        </div>
        <div class="col-12">
          <!-- Button -->
          <%= f.submit class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>