config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'events/index'
  root 'events#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, only: %i[new create]
  resources :events do
    collection do
      get :future
      get :past
      get :woman
    end
    resource :attendance, only: %i[create destroy], module: :events
    resource :bookmark, only: %i[create destroy], module: :events
    resources :comments, only: %i[create destroy], module: :events
  end

  resources :notifications, only: %i[index show]
  namespace :notifications do
    resource :all_reads, only: %i[create]
  end

  namespace :mypage do
    root 'event_calendars#show'
    resource :event_calendar, only: %i[show]
    resources :notifications, only: %i[index]
    resource :notification_setting, only: %i[show update]
    resource :profile, only: %i[show update] do
      resource :avatar, only: %i[destroy], module: :profiles
    end
    resource :password_change, only: %i[show update]
  end

  namespace :api, defaults: { format: :json } do
    namespace :me do
      resources :events, only: %i[index]
    end
  end
end

app/views/shared/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="text-muted">© 2021 Company, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
  </footer>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-default">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">MOKUMOKU</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <%= search_form_for @q || Event.ransack(params[:q]), url: @search_path || events_path, class: 'd-flex align-items-center' do |f| %>
        <%= f.search_field :title_or_content_cont, class: 'form-control form-control-sm me-2', placeholder: 'もくもく会検索' %>
        <%= f.submit '検索', class: 'btn btn-outline-success btn-sm'  %>
      <% end %>
      <% if logged_in? %>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item d-flex align-items-center">
            <%= link_to 'もくもく会を作る', new_event_path, class: 'btn btn-primary btn-sm me-2' %>
          </li>
          <%= render 'shared/notifications' %>
          <li class="dropdown ms-2 d-inline-block">
            <a class="rounded-circle" href="#" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
              <div class="avatar avatar-md">
                <%= image_tag current_user.decorate.avatar, class: 'rounded-circle avatar-sm' %>
              </div>
            </a>
            <div class="dropdown-menu dropdown-menu-end">
              <div class="dropdown-item">
                <div class="d-flex">
                  <div class="avatar avatar-md">
                    <%= image_tag current_user.decorate.avatar, class: 'rounded-circle avatar-sm' %>
                  </div>
                  <div class="ms-3 lh-1">
                    <h5 class="mb-1"><%= current_user.name %></h5>
                    <p class="mb-0 text-muted"><%= current_user.email %></p>
                  </div>
                </div>
              </div>
              <div class="dropdown-divider"></div>
              <ul class="list-unstyled">
                <li>
                  <%= link_to mypage_root_path, class: 'dropdown-item' do %>
                    <i class="bi bi-calendar-check me-2"></i>マイページ
                  <% end %>
                </li>
                <li>
                  <a class="dropdown-item" href="/mypage/profile">
                    <i class="bi bi-person me-2"></i>プロフィール
                  </a>
                </li>
              </ul>
              <div class="dropdown-divider"></div>
              <ul class="list-unstyled">
                <li>
                  <%= link_to logout_path, method: :delete, data: { confirm: 'ログアウトします' }, class: 'dropdown-item' do %>
                    <i class="bi bi-box-arrow-left me-2"></i>ログアウト
                  <% end %>
                </li>
              </ul>
            </div>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 d-flex align-items-center">
          <li class="nav-item">
            <%= link_to 'ログイン', login_path, class: 'nav-link me-2' %>
          </li>
          <li class="nav-item">
            <%= link_to 'サインアップ', new_user_path, class: 'btn btn-primary btn-sm' %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_notifications.html.erb
<li class="dropdown d-inline-block stopevent">
  <a class="btn btn-light btn-icon rounded-circle text-muted <%= "indicator indicator-primary" if current_user.notifications.unread.present? %>" href="#" role="button" id="dropdownNotificationSecond" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <i class="bi bi-bell"> </i>
  </a>
  <div class="dropdown-menu dropdown-menu-end dropdown-menu-lg" aria-labelledby="dropdownNotificationSecond">
    <div>
      <div class="border-bottom px-3 pb-3 d-flex justify-content-between align-items-center">
        <span class="h5 mb-0">Notifications</span>
        <a href="# " class="text-muted"><span class="align-middle"><i class="fe fe-settings me-1"></i></span></a>
      </div>
      <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: auto; height: 300px;">
        <ul class="list-group list-group-flush notification-list-scroll " style="overflow-y: scroll; width: auto; height: 300px;">
          <%= render partial: 'notifications/notification', collection: current_user.notifications.with_avatar.order(created_at: :desc).limit(10) %>
        </ul>
        <div class="slimScrollBar" style="background: rgb(0, 0, 0); width: 7px; position: absolute; top: 0px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 1px; height: 154.905px;"></div>
        <div class="slimScrollRail" style="width: 7px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 1px;"></div>
      </div>
      <div class="border-top px-3 pt-3 pb-0">
        <a href="/mypage/notifications" class="text-link fw-semi-bold">See all Notifications</a>
      </div>
    </div>
  </div>
</li>