config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  get 'events/index'
  root 'events#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  resources :users, only: %i[new create]
  resources :events do
    collection do
      get :future
      get :past
      get :woman
    end
    resource :attendance, only: %i[create destroy], module: :events
    resource :bookmark, only: %i[create destroy], module: :events
    resources :comments, only: %i[create destroy], module: :events
  end

  resources :notifications, only: %i[index show]
  namespace :notifications do
    resource :all_reads, only: %i[create]
  end

  namespace :mypage do
    root 'event_calendars#show'
    resource :event_calendar, only: %i[show]
    resources :notifications, only: %i[index]
    resource :notification_setting, only: %i[show update]
    resource :profile, only: %i[show update] do
      resource :avatar, only: %i[destroy], module: :profiles
    end
    resource :password_change, only: %i[show update]
  end

  namespace :api, defaults: { format: :json } do
    namespace :me do
      resources :events, only: %i[index]
    end
  end
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  include Notifiable
  belongs_to :prefecture
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :commented_users, through: :comments, class_name: 'User', source: :user
  has_many :attendances, dependent: :destroy, class_name: 'EventAttendance'
  has_many :attendees, through: :attendances, class_name: 'User', source: :user
  has_many :bookmarks, dependent: :destroy
  has_one_attached :thumbnail

  scope :future, -> { where('held_at > ?', Time.current) }
  scope :past, -> { where('held_at <= ?', Time.current) }

  with_options presence: true do
    validates :title
    validates :content
    validates :held_at
  end

  def past?
    held_at < Time.current
  end

  def future?
    !past?
  end
end

app/controllers/api/me/events_controller.rb
# frozen_string_literal: true

class Api::Me::EventsController < ApplicationController
  before_action :require_login

  def index
    @events = current_user.attend_events
  end
end

app/controllers/events/attendances_controller.rb
# frozen_string_literal: true

class Events::AttendancesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    event_attendance = current_user.attend(@event)
    (@event.attendees - [current_user] + [@event.user]).uniq.each do |user|
      NotificationFacade.attended_to_event(event_attendance, user)
    end
    redirect_back(fallback_location: root_path, success: '参加の申込をしました')
  end

  def destroy
    @event = Event.find(params[:event_id])
    current_user.cancel_attend(@event)
    redirect_back(fallback_location: root_path, success: '申込をキャンセルしました')
  end
end

app/controllers/events/bookmarks_controller.rb
# frozen_string_literal: true

class Events::BookmarksController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    bookmark = current_user.bookmark(@event)
    NotificationFacade.liked_event(bookmark, @event.user)
  end

  def destroy
    @event = Event.find(params[:event_id])
    current_user.unbookmark(@event)
  end
end

app/controllers/events/comments_controller.rb
# frozen_string_literal: true

class Events::CommentsController < ApplicationController
  # rubocop:disable Metrics/AbcSize
  def create
    @event = Event.find(params[:event_id])
    comment = current_user.comments.build(comment_params.merge(event_id: @event.id))
    if comment.save
      ([*@event.commented_users, *@event.attendees, @event.user] - [current_user]).uniq.each do |user|
        NotificationFacade.commented_to_event(comment, user)
      end
      redirect_to event_path(@event)
    else
      render 'events/show'
    end
  end
  # rubocop:enable Metrics/AbcSize

  def destroy; end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def index
    @q = Event.future.ransack(params[:q])
    @events = @q.result(distinct: true).includes(:bookmarks, :prefecture, user: { avatar_attachment: :blob })
                .order(created_at: :desc).page(params[:page])
  end

  def future
    @q = Event.future.ransack(params[:q])
    @events = @q.result(distinct: true).includes(:bookmarks, :prefecture, user: { avatar_attachment: :blob })
                .order(held_at: :asc).page(params[:page])
    @search_path = future_events_path
    render :index
  end

  def past
    @q = Event.past.ransack(params[:q])
    @events = @q.result(distinct: true).includes(:bookmarks, :prefecture, user: { avatar_attachment: :blob })
                .order(held_at: :desc).page(params[:page])
    @search_path = past_events_path
    render :index
  end

  def woman 
    @q = Event.ransack(params[:q]) 
    @events = @q.result(distinct: true).includes(:bookmarks, :prefecture, user: { avatar_attachment: :blob }) 
                .where(only_woman: true)
                .order(created_at: :desc).page(params[:page]) 
    @search_path = woman_events_path 
    render :index 
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      User.all.find_each do |user|
        NotificationFacade.created_event(@event, user)
      end

      redirect_to event_path(@event)
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = current_user.events.find(params[:id])
  end

  def update
    @event = current_user.events.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      render :edit
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :content, :held_at, :prefecture_id, :only_woman, :thumbnail)
  end
end

app/views/events/_attendee.html.erb
<li>
  <div class="d-flex align-items-center gap-2 mb-3">
    <%= image_tag attendee.decorate.avatar, class: 'rounded-circle avatar-md' %>
    <%= attendee.name %>
  </div>
</li>

app/views/events/_comment.html.erb
<li>
  <div class="d-flex align-items-center gap-2 mb-3">
    <%= image_tag comment.user.decorate.avatar, class: 'rounded-circle avatar-sm' %>
    <%= comment.user.name %>
  </div>
  <%= simple_format comment.content %>
  <div class="text-end">
    <span class="fs-6 text-muted">
      <%= l comment.created_at, format: :short %>
    </span>
  </div>
  <hr />
</li>

app/views/events/_event.html.erb
<div class="col">
  <div class="card h-100">
    <%= link_to event_path(event) do %>
      <%= image_tag event.decorate.thumbnail, class: 'card-img-top border-bottom' %>
    <% end %>
    <div class="card-body">
      <h4 class="card-title fw-bold">
        <%= link_to event.title, event_path(event)  %>
      </h4>
      <p class="card-text"><%= event.content %></p>
      <hr />
      <div class="d-flex justify-content-between">
        <div>
          <i class="bi bi-geo-alt"></i>
          <%= event.prefecture.name %>
        </div>
        <div>
          <i class="bi bi-calendar"></i>
          <%= l event.held_at, format: :short %>
        </div>
      </div>
      <hr />
      <div class="d-flex align-items-center justify-content-between">
        <div class="d-flex align-items-center gap-3">
          <%= image_tag event.user.decorate.avatar, class: 'avatar-sm rounded-circle' %>
          <%= event.user.name %>
        </div>
        <% if logged_in? %>
          <div id="js-event-bookmark-<%= event.id %>">
            <% if current_user.bookmarked?(event) %>
              <%= render 'events/bookmarks/unbookmark', event: event %>
            <% else %>
              <%= render 'events/bookmarks/bookmark', event: event %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with model: @event do |f| %>
  <%#= render 'shared/error_messages', object: f.object %>
  <div class="mb-3">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', rows: 10 %>
  </div>
  <div class="mb-3">
    <%= f.label :held_at %>
    <%= f.datetime_field :held_at, class: 'form-control' %>
  </div>
  <div class="mb-3">
    <%= f.label :prefecture_id %>
    <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, {}, class: 'form-select' %>
  </div>
  <% if current_user.woman? %>
  <div class="mb-3">
    <%= f.label :only_woman %>
    <%= f.check_box :only_woman, {checked: (@current_user == "woman"), value: true } %>
  </div>
  <% end %>
  <div class="mb-3">
    <%= f.label :thumbnail %>
    <%= f.file_field :thumbnail, class: 'form-control js-file-select-preview mb-3', accept: 'image/*', data: { target: '#preview-target' } %>
    <%= image_tag f.object.decorate.thumbnail, id: 'preview-target', class: 'w-100 border' %>
  </div>
    <%= f.submit '登録', class: 'btn btn-primary' %>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <div class="card">
        <div class="card-header">
          <i class="bi bi-calendar me-2"></i>
          <span>もくもく会編集</span>
        </div>
        <div class="card-body">
          <%= render 'form', event: @event %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/index.html.erb
<div class="container">
  <ul class="nav nav-lb-tab mb-6 justify-content-center" id="tab" role="tablist">
    <li class="nav-item ms-0" role="presentation">
      <a class="nav-link <%= active_if('events#index') %>" href="/" role="tab">新着イベント</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link <%= active_if('events#future') %>" href="/events/future" role="tab">直近イベント</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link <%= active_if('events#past') %>" href="/events/past" role="tab">過去イベント</a>
    </li>
    <li class="nav-item" role="presentation">
      <a class="nav-link <%= active_if('events#woman') %>" href="/events/woman" role="tab">女性限定</a>
    </li>
  </ul>

  <div class="row row-cols-1 row-cols-md-3 g-4 mb-3">
    <%= render @events %>
  </div>
  <div class="mx-auto">
    <%= paginate @events %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <div class="card">
        <div class="card-header">
          <i class="bi bi-calendar me-2"></i>
          <span>もくもく会作成</span>
        </div>
        <div class="card-body">
          <%= render 'form', event: @event %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-8">
      <div class="card mb-3">
        <div class="card-body">
          <div class="d-flex align-items-center">
            <div class="p-3">
              <h5 class="m-0">
                <span class="badge bg-secondary">
                  <%= l @event.held_at.to_date, format: :short %>
                </span>
              </h5>
            </div>
            <h1>
              <%= @event.title %>
            </h1>
            <% if logged_in? %>
              <div class="ms-auto">
                <% if current_user.own?(@event) %>
                  <span class="me-2">
                    <%= link_to edit_event_path(@event) do  %>
                      <i class="bi bi-pencil"></i>
                    <% end %>
                  </span>
                <% end %>
                <span id="js-event-bookmark-<%= @event.id %>">
                  <% if current_user.bookmarked?(@event) %>
                    <%= render 'events/bookmarks/unbookmark', event: @event %>
                  <% else %>
                    <%= render 'events/bookmarks/bookmark', event: @event %>
                  <% end %>
                </span>
              </div>
            <% end %>
          </div>
          <div>
            <%= image_tag @event.decorate.thumbnail, class: 'w-100' %>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="card-header">
          <i class="bi bi-info-circle"></i>
          イベントの説明
        </div>
        <div class="card-body">
          <%= simple_format @event.content %>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-4">
      <div class="card mb-3">
        <div class="card-header">
          <i class="bi bi-person"></i>
          主催者情報
        </div>
        <div class="card-body">
          <div class="d-flex align-items-center gap-3 mb-3">
            <%= image_tag @event.user.decorate.avatar, class: 'rounded-circle avatar-lg' %>
            <%= @event.user.name %>
          </div>
          <div class="p-3 bg-light">
            イベント数
            <%= @event.user.events.size %>
            回
          </div>
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-body">
          <div class="bg-primary text-center p-2 text-white rounded mb-3">
            <% if @event.past? %>
              開催済み
            <% else %>
              開催前
            <% end %>
          </div>
          <h3 class="text-center">
            開催日時
          </h3>
          <h4 class="text-center">
            <%= l @event.held_at, format: :short %>
          </h4>
          <hr />
          <div class="text-center">
            <% if logged_in? %>
              <% if !current_user.owner?(@event) %>
                <% if @event.only_woman ==true && current_user.gender != "女性" %>
                  <h3>女性限定</h3>
                <% else %>
                  <% if current_user.attend?(@event) %>
                    <%= link_to 'キャンセルする',
                              event_attendance_url(@event),
                              class: 'btn btn-primary',
                              method: :delete,
                              data: { confirm: 'キャンセルします' }
                    %>
                  <% else %>
                    <%= link_to 'このもくもく会に参加する',
                              event_attendance_url(@event),
                              class: 'btn btn-primary',
                              method: :post,
                              data: { confirm: '申し込みます' }
                    %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>  
          </div>
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-header">
          <i class="bi bi-people"></i>
          参加者（<%= @event.attendees.size %>人）
        </div>
        <div class="card-body">
           <ul class="list-unstyled">
             <%= render partial: 'events/attendee', collection: @event.attendees %>
           </ul>
        </div>
      </div>

      <div class="card">
        <div class="card-header">
          <i class="bi bi-chat"></i>
          コメント
        </div>
        <div class="card-body">
          <ul class="list-unstyled">
            <%= render partial: 'events/comment', collection: @event.comments %>

          </ul>
          <%= form_with model: [@event, @comment || Comment.new] do |f| %>
            <div class="mb-3">
              <%= f.text_area :content, class: 'form-control' %>
            </div>
            <%= f.submit class: 'btn btn-primary btn-sm' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>